spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: norepqw2
    driver-class-name: org.postgresql.Driver
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

server:
  port: 8081

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: debug


